name: SkillGiver
main: com.stealthyone.bukkit.McmmoSkillGiver.BasePlugin
version: 1.2.1
website: http://stealthyone.com/
description: Simplifed commands for McMMO skill-related commands
author: Stealth2800
commands:
  skillgiver:
    description: 'General plugin information'
    usage: '/skillgiver'
  mmoaward:
    description: 'Awards a player levels in all skills'
    usage: '/mmoaward <player> <levels>'